import type { Metadata } from "next";
import { PrimeReactProvider } from "primereact/api";
import { IBM_Plex_Sans_Thai } from "next/font/google";
import PageLayout from "./components/PageLayout";
import "primereact/resources/themes/tailwind-light/theme.css";
import "primeicons/primeicons.css";
import "./globals.css";

const IBM = IBM_Plex_Sans_Thai({
  subsets: ["latin", "thai"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "MOC | KK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PrimeReactProvider>
      <html lang="en">
        <body className={`${IBM.className} antialiased`}>
          <PageLayout>{children}</PageLayout>
        </body>
      </html>
    </PrimeReactProvider>
  );
}
